# Generated by Django 5.2.4 on 2025-10-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('girls', '0002_rename_category_categoryoff_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contestant',
            new_name='ContestantOff',
        ),
        migrations.RenameModel(
            old_name='Program',
            new_name='Program0ff',
        ),
        migrations.RenameModel(
            old_name='TeamPoints',
            new_name='TeamPointsOff',
        ),
    ]
