# Generated by Django 5.2.4 on 2025-09-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_participation_points_awarded"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="is_group",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
