# Generated by Django 5.2.4 on 2025-10-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_participation_marks_added_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="members_count",
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
