# Generated by Django 5.2.4 on 2025-09-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='members_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
