# Generated by Django 5.2.4 on 2026-07-19 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_festday_stage_program_buffer_margin_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='festday',
            name='end_time',
            field=models.TimeField(default='21:00', help_text='Operating end time for this day'),
        ),
        migrations.AddField(
            model_name='festday',
            name='start_time',
            field=models.TimeField(default='09:00', help_text='Operating start time for this day'),
        ),
        migrations.AddField(
            model_name='program',
            name='preferred_stage',
            field=models.ForeignKey(blank=True, help_text='Priority stage venue for popular events', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_programs', to='core.stage'),
        ),
        migrations.AddField(
            model_name='program',
            name='presentation_mode',
            field=models.CharField(choices=[('SEQUENTIAL', 'Per Participant (Sequential)'), ('SIMULTANEOUS', 'All-at-Once (Simultaneous/Written)')], default='SEQUENTIAL', help_text='Sequential (Speech/Song) vs Simultaneous (Essay/Drawing)', max_length=15),
        ),
        migrations.AlterField(
            model_name='program',
            name='duration_per_participant',
            field=models.PositiveIntegerField(default=5, help_text='Duration in minutes per participant (or total fixed mins if simultaneous)'),
        ),
    ]
