# Generated by Django 5.2.4 on 2026-07-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_festday_end_time_festday_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupparticipation',
            name='code_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
