# Generated by Django 5.2.4 on 2026-07-29 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_groupparticipation_code_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupparticipation',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_groups', to='core.contestant'),
        ),
    ]
