# Generated by Django 5.2.4 on 2026-08-08

from django.db import migrations

def populate_combined_categories(apps, schema_editor):
    Category = apps.get_model('core', 'Category')
    
    # 1. Handle GENERAL category
    general_cat = Category.objects.filter(name__iexact='GENERAL').first()
    if general_cat:
        general_cat.is_common = True
        general_cat.save()
        base_cats = Category.objects.filter(name__in=['APEX', 'VERTEX', 'CORTEX'])
        if base_cats.exists():
            general_cat.included_categories.set(base_cats)

    # 2. Handle CATEGORY A category
    cat_a = Category.objects.filter(name__iexact='CATEGORY A').first()
    if cat_a:
        cat_a.is_common = True
        cat_a.save()
        base_cats_a = Category.objects.filter(name__in=['APEX', 'VERTEX'])
        if base_cats_a.exists():
            cat_a.included_categories.set(base_cats_a)

def rollback_combined_categories(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_category_included_categories_category_is_common'),
    ]

    operations = [
        migrations.RunPython(populate_combined_categories, rollback_combined_categories),
    ]
