# Generated by Django 5.2.4 on 2026-08-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_populate_combined_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='student_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Class'),
        ),
    ]
