# Generated by Django 5.2.4 on 2026-08-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_contestant_student_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programschedule',
            options={'ordering': ['fest_day__day_number', 'stage', 'order', 'start_time']},
        ),
        migrations.AddField(
            model_name='programschedule',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Order/sequence of the program on this stage for the day'),
        ),
    ]
