# Generated by Django 5.2.4 on 2026-08-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_programschedule_options_programschedule_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='fest_days',
            field=models.ManyToManyField(blank=True, help_text='Fest days when this stage is active/available', related_name='stages', to='core.festday'),
        ),
    ]
